title = "Enceintes-qui-buzz"
slug = "tutorials/Enceintes-qui-buzz/buzz"
date = "2026-09-06"

[author]
pseudo = "Gantil"
name = "Gantil"
role = "Modérateur"
avatar = "/avatars/gantil.png"

[metadata]
title_keyword = "Buzz"
aux_keywords = ["Enceinte", "Audio", "Gresillement"]
misc_keywords = ["Electrique", "Son"]
