title = "Douanes"
slug = "tutorials/Attention-a-la-douane/douanes"
date = "2024-11-26"

[author]
pseudo = "l.heywang"
name = "l.heywang"
role = "Admin / Helper"
avatar = "/avatars/l.heywang.png"

[metadata]
title_keyword = "douanes"
aux_keywords = ["achats", "Aliexpress", "taxes"]
misc_keywords = ["TVA", "UE", "CPU"]
