title = "Le-minage-est-il-mauvais"
slug = "commu/Le-minage-est-il-mauvais/minage"
date = "2021-04-27"

[author]
pseudo = "Ted"
name = "Ted"
role = "Helper"
avatar = "/avatars/ted.png"

[metadata]
title_keyword = "Minage"
aux_keywords = ["GPU", "Cryptos", "Usure"]
misc_keywords = []
