title = "De-texte-a-processeur"
slug = "articles/De-texte-a-processeur/rtl"
date = "2026-04-26"

[author]
pseudo = "l.heywang"
name = "l.heywang"
role = "Admin / Helper"
avatar = "/avatars/l.heywang.png"

[metadata]
title_keyword = "CPU"
aux_keywords = ["Design", "RTL", "Conception"]
misc_keywords = ["Specification", "Flow", "Texte"]
