title = "Casques-micro-gaming"
slug = "tutorials/Casques-micro-gaming/mics"
date = "2023-09-26"

[author]
pseudo = "Deto"
name = "Deto"
role = "Helper"
avatar = "/avatars/deto.png"

[metadata]
title_keyword = "Micro"
aux_keywords = ["Jack", "4", "3", "poles"]
misc_keywords = ["casque", "son", "prise"]
