title = "Un-i5-est-un-i9-rate"
slug = "articles/Un-i5-est-un-i9-rate/binning"
date = "2025-01-25"

[author]
pseudo = "l.heywang"
name = "l.heywang"
role = "Admin / Helper"
avatar = "/avatars/l.heywang.png"

[metadata]
title_keyword = "Binning"
aux_keywords = ["CPU", "I5", "Rate"]
misc_keywords = ["Tri", "Desactivés", "Die", "Wafer"]
