title = "Bien-placer-son-micro"
slug = "tutorials/Bien-placer-son-micro/mics"
date = "2026-09-10"

[author]
pseudo = "Yometa"
name = "Yometa"
role = "Membre"
avatar = "/avatars/yometa.png"

[metadata]
title_keyword = "Micro"
aux_keywords = ["Placement", "Audio", "Son"]
misc_keywords = ["XLR", "USB", "Source"]
