title = "Entre-vitesse-et-stabilité"
slug = "articles/Entre-vitesse-et-stabilité/xmp"
date = "2026-09-08"

[author]
pseudo = "l.heywang"
name = "l.heywang"
role = "Admin / Helper"
avatar = "/avatars/l.heywang.png"

[metadata]
title_keyword = "XMP"
aux_keywords = ["RAM", "OC", "Frequence"]
misc_keywords = ["Profil", "Instabilite", "CPU"]
