title = "Garanties-menteuses"
slug = "commu/Garanties-menteuses/garantie"
date = "2024-11-19"

[author]
pseudo = "l.heywang"
name = "l.heywang"
role = "Admin / Helper"
avatar = "/avatars/l.heywang.png"

[metadata]
title_keyword = "Garantie"
aux_keywords = ["Fiabilite", "Durabilite", "Default"]
misc_keywords = ["Retours", "Baignoire", "Entretien"]
